packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@ant-design/compatible": 5.1.5
  "@ant-design/fast-color": 3.0.1
  "@ant-design/icons": 6.3.4
  "@rc-component/steps": 1.2.3
  "@rc-component/util": 1.13.0
  "@rsbuild/core": 2.2.8
  "@rsbuild/plugin-react": 2.1.0
  "@types/node": 24.1.0
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0
  antd: 6.6.5
  antd-style: 4.1.0
  clsx: 2.1.1
  react: 19.3.0
  react-dom: 19.3.0
  swr: 2.5.1
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-darwin-arm64@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-darwin-x64@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-linux-x64-musl@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0-rc.0"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0-rc.0"
  - vite-plus@1.0.0-rc.0
allowBuilds:
  core-js: true
