import type { ThemeConfig } from "antd";
import { theme } from "antd";

import { jojoColors, jojoInkShadow, jojoInkShadowLg, jojoInkShadowSm } from "./colors.ts";
import { jojoMotion, jojoPoseEase } from "./motion.ts";

/**
 * Ant Design theme — Hirohiko Araki / JoJo’s Bizarre Adventure.
 *
 * Keywords: bold thick black outlines, sharp angular / sculptural anatomy,
 * exaggerated dynamic poses (pointing-hand tension), vibrant saturated
 * non-naturalistic color, high-fashion pattern & jewelry accents, dramatic
 * solid-black shading — not soft anime.
 *
 * For pose-skew, hatch texture, and uppercase chrome, also import
 * `@clawd-cook/antd-jojo-theme/styles.css` and wrap with `jojoRootClass`.
 */
export const jojoTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  cssVar: { key: "jojo" },
  token: {
    colorPrimary: jojoColors.purple,
    colorSuccess: jojoColors.teal,
    colorWarning: jojoColors.gold,
    colorError: jojoColors.crimson,
    colorInfo: jojoColors.cyan,

    colorTextBase: jojoColors.ink,
    colorBgBase: jojoColors.sky,

    colorText: jojoColors.ink,
    colorTextSecondary: jojoColors.inkMuted,
    colorTextTertiary: "#5C4A78",
    colorTextQuaternary: "#8A769E",

    colorLink: jojoColors.magenta,
    colorLinkHover: jojoColors.purpleHot,
    colorLinkActive: jojoColors.purpleDeep,

    // Flat paper panels — no soft marble gradient feel
    colorBgContainer: jojoColors.paper,
    colorBgElevated: jojoColors.paper,
    colorBgLayout: jojoColors.sky,
    colorBgSpotlight: jojoColors.shade,
    colorBgMask: "rgba(26, 10, 46, 0.72)",
    colorBgSolid: jojoColors.ink,
    colorBgSolidHover: jojoColors.shade,
    colorFillSecondary: jojoColors.paperDeep,
    colorFillTertiary: jojoColors.standAura,
    colorFillQuaternary: "rgba(107, 31, 160, 0.12)",

    colorBorder: jojoColors.ink,
    colorBorderSecondary: jojoColors.ink,

    // Flat saturated fills (pop / cover art), not pastel wash
    colorPrimaryBg: jojoColors.standAura,
    colorPrimaryBgHover: "#C9A0FF",
    colorPrimaryBorder: jojoColors.ink,
    colorPrimaryBorderHover: jojoColors.ink,
    colorPrimaryHover: jojoColors.purpleHot,
    colorPrimaryActive: jojoColors.purpleDeep,
    colorPrimaryText: jojoColors.purple,
    colorPrimaryTextHover: jojoColors.purpleHot,
    colorPrimaryTextActive: jojoColors.purpleDeep,

    colorSuccessBg: jojoColors.teal,
    colorSuccessBorder: jojoColors.ink,
    colorSuccessText: jojoColors.ink,
    colorWarningBg: jojoColors.gold,
    colorWarningBorder: jojoColors.ink,
    colorWarningText: jojoColors.ink,
    colorErrorBg: jojoColors.crimson,
    colorErrorBorder: jojoColors.ink,
    colorErrorText: jojoColors.paper,
    colorInfoBg: jojoColors.cyan,
    colorInfoBorder: jojoColors.ink,
    colorInfoText: jojoColors.ink,

    // Kill soft focus rings — ink contour only
    controlOutlineWidth: 0,
    controlOutline: "transparent",
    controlTmpOutline: "transparent",

    // Thick ink contour
    lineWidth: 4,
    lineWidthBold: 5,
    lineType: "solid",
    lineWidthFocus: 4,

    // Sharp sculpted edges — classical anatomy / chiselled jaw
    borderRadius: 0,
    borderRadiusXS: 0,
    borderRadiusSM: 0,
    borderRadiusLG: 0,
    borderRadiusOuter: 0,

    controlHeight: 44,
    controlHeightSM: 36,
    controlHeightLG: 52,

    fontSize: 15,
    fontSizeLG: 18,
    fontSizeXL: 22,
    fontSizeHeading1: 42,
    fontSizeHeading2: 32,
    fontSizeHeading3: 26,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontWeightStrong: 900,
    // Condensed fashion-editorial type
    fontFamily:
      '"Arial Narrow", "Futura Condensed", "Helvetica Neue Condensed", Impact, "Gill Sans", sans-serif',

    boxShadow: jojoInkShadow,
    boxShadowSecondary: jojoInkShadowLg,
    boxShadowTertiary: jojoInkShadowSm,

    // Pose snap — tension, not soft ease
    motionDurationFast: jojoMotion.fast,
    motionDurationMid: jojoMotion.mid,
    motionDurationSlow: jojoMotion.slow,
    motionEaseInOut: jojoPoseEase,
    motionEaseOut: jojoPoseEase,
    motionEaseOutBack: jojoPoseEase,
    motionEaseInBack: jojoPoseEase,
    motionEaseInOutCirc: jojoPoseEase,
    motionEaseOutCirc: jojoPoseEase,
    motionEaseInQuint: jojoPoseEase,
    motionEaseOutQuint: jojoPoseEase,
  },
  components: {
    Button: {
      primaryShadow: jojoInkShadow,
      defaultShadow: jojoInkShadow,
      dangerShadow: jojoInkShadow,
      fontWeight: 900,
      contentFontSize: 15,
      contentFontSizeLG: 17,
      borderColorDisabled: jojoColors.inkMuted,
      defaultBorderColor: jojoColors.ink,
      defaultColor: jojoColors.ink,
      defaultBg: jojoColors.paper,
      defaultHoverBg: jojoColors.gold,
      defaultHoverBorderColor: jojoColors.ink,
      defaultHoverColor: jojoColors.ink,
      defaultActiveBg: jojoColors.goldDeep,
      defaultActiveBorderColor: jojoColors.ink,
      defaultActiveColor: jojoColors.ink,
      primaryColor: jojoColors.paper,
      dangerColor: jojoColors.paper,
      textHoverBg: jojoColors.paperDeep,
      borderRadius: 0,
      paddingInline: 24,
      paddingInlineLG: 28,
      controlHeight: 44,
      controlHeightLG: 52,
    },
    Input: {
      activeShadow: jojoInkShadowSm,
      hoverBorderColor: jojoColors.magenta,
      activeBorderColor: jojoColors.ink,
      borderRadius: 0,
      colorBgContainer: jojoColors.paper,
      paddingBlock: 8,
      paddingInline: 14,
    },
    InputNumber: {
      activeShadow: jojoInkShadowSm,
      hoverBorderColor: jojoColors.magenta,
      activeBorderColor: jojoColors.ink,
      borderRadius: 0,
    },
    Select: {
      optionSelectedBg: jojoColors.standAura,
      optionActiveBg: jojoColors.paperDeep,
      optionSelectedFontWeight: 800,
      borderRadius: 0,
      colorBgContainer: jojoColors.paper,
      selectorBg: jojoColors.paper,
    },
    Cascader: {
      optionSelectedBg: jojoColors.standAura,
      dropdownHeight: 220,
    },
    DatePicker: {
      activeShadow: jojoInkShadowSm,
      hoverBorderColor: jojoColors.magenta,
      activeBorderColor: jojoColors.ink,
      cellActiveWithRangeBg: jojoColors.standAura,
      cellHoverBg: jojoColors.paperDeep,
    },
    Card: {
      borderRadiusLG: 0,
      colorBgContainer: jojoColors.paper,
      boxShadow: jojoInkShadow,
      colorBorderSecondary: jojoColors.ink,
      headerBg: jojoColors.gold,
      headerFontSize: 16,
      headerHeight: 52,
    },
    Modal: {
      borderRadiusLG: 0,
      boxShadow: jojoInkShadowLg,
      contentBg: jojoColors.paper,
      headerBg: jojoColors.gold,
      titleColor: jojoColors.ink,
      titleFontSize: 18,
      footerBg: jojoColors.sky,
    },
    Drawer: {
      colorBgElevated: jojoColors.paper,
      footerPaddingBlock: 16,
      footerPaddingInline: 20,
    },
    Alert: {
      borderRadiusLG: 0,
      withDescriptionPadding: "14px 18px",
      defaultPadding: "10px 14px",
    },
    Tag: {
      borderRadiusSM: 0,
      defaultBg: jojoColors.paperDeep,
      defaultColor: jojoColors.ink,
    },
    Tooltip: {
      borderRadius: 0,
      colorBgSpotlight: jojoColors.ink,
      colorTextLightSolid: jojoColors.gold,
    },
    Popover: {
      borderRadiusLG: 0,
      colorBgElevated: jojoColors.paper,
    },
    Dropdown: {
      borderRadiusLG: 0,
      colorBgElevated: jojoColors.paper,
      paddingBlock: 6,
    },
    Notification: {
      width: 384,
      borderRadiusLG: 0,
      colorSuccessBg: jojoColors.teal,
      colorErrorBg: jojoColors.crimson,
      colorInfoBg: jojoColors.cyan,
      colorWarningBg: jojoColors.gold,
    },
    Message: {
      contentBg: jojoColors.paper,
      contentPadding: "12px 16px",
      borderRadiusLG: 0,
    },
    Progress: {
      circleTextColor: jojoColors.ink,
      defaultColor: jojoColors.magenta,
      remainingColor: jojoColors.shade,
      lineBorderRadius: 0,
    },
    Slider: {
      trackBg: jojoColors.magenta,
      trackHoverBg: jojoColors.purpleHot,
      handleColor: jojoColors.gold,
      handleActiveColor: jojoColors.skyHot,
      handleSize: 18,
      handleSizeHover: 22,
      handleLineWidth: 3,
      handleLineWidthHover: 4,
      railBg: jojoColors.shade,
      railHoverBg: jojoColors.inkMuted,
      railSize: 10,
      dotBorderColor: jojoColors.ink,
      dotActiveBorderColor: jojoColors.magenta,
      dotSize: 10,
    },
    Switch: {
      trackHeight: 28,
      trackMinWidth: 56,
      handleSize: 24,
      innerMinMargin: 6,
      innerMaxMargin: 28,
    },
    Checkbox: {
      borderRadiusSM: 0,
      size: 18,
    },
    Radio: {
      radioSize: 20,
      dotSize: 10,
      wrapperMarginInlineEnd: 12,
    },
    Steps: {
      iconSize: 40,
      iconSizeSM: 28,
      titleLineHeight: 1.15,
    },
    Layout: {
      bodyBg: jojoColors.sky,
      footerBg: jojoColors.sky,
      headerBg: jojoColors.gold,
      headerColor: jojoColors.ink,
      headerHeight: 64,
      headerPadding: "0 28px",
      siderBg: jojoColors.shade,
      lightSiderBg: jojoColors.shade,
      triggerBg: jojoColors.magenta,
      triggerColor: jojoColors.gold,
      triggerHeight: 48,
      lightTriggerBg: jojoColors.magenta,
      lightTriggerColor: jojoColors.gold,
      zeroTriggerWidth: 48,
      zeroTriggerHeight: 48,
    },
    Menu: {
      activeBarBorderWidth: 0,
      activeBarWidth: 6,
      itemBg: "transparent",
      subMenuItemBg: "transparent",
      itemColor: "rgba(255, 248, 231, 0.78)",
      itemHoverColor: jojoColors.gold,
      itemSelectedColor: jojoColors.gold,
      subMenuItemSelectedColor: jojoColors.gold,
      itemHoverBg: "rgba(245, 197, 24, 0.22)",
      itemSelectedBg: "rgba(230, 0, 122, 0.48)",
      itemActiveBg: "rgba(230, 0, 122, 0.32)",
      itemBorderRadius: 0,
      itemMarginInline: 8,
      itemHeight: 48,
      iconSize: 16,
      darkItemBg: "transparent",
      darkItemColor: "rgba(255, 248, 231, 0.78)",
      darkItemHoverBg: "rgba(245, 197, 24, 0.22)",
      darkItemHoverColor: jojoColors.gold,
      darkItemSelectedBg: "rgba(230, 0, 122, 0.48)",
      darkItemSelectedColor: jojoColors.gold,
      darkSubMenuItemBg: "transparent",
      darkPopupBg: jojoColors.shade,
      popupBg: jojoColors.paper,
    },
    Table: {
      headerBg: jojoColors.gold,
      headerColor: jojoColors.ink,
      headerSortActiveBg: jojoColors.goldDeep,
      headerSortHoverBg: jojoColors.skyHot,
      headerFilterHoverBg: jojoColors.paperDeep,
      borderColor: jojoColors.ink,
      rowHoverBg: jojoColors.standAura,
      rowSelectedBg: "rgba(230, 0, 122, 0.16)",
      rowSelectedHoverBg: "rgba(230, 0, 122, 0.28)",
      headerBorderRadius: 0,
      footerBg: jojoColors.paperDeep,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
    },
    Tabs: {
      itemSelectedColor: jojoColors.magenta,
      inkBarColor: jojoColors.magenta,
      itemHoverColor: jojoColors.purpleHot,
      itemActiveColor: jojoColors.purpleDeep,
      titleFontSize: 15,
      horizontalItemPadding: "12px 18px",
      cardBg: jojoColors.paper,
      cardHeight: 44,
    },
    Segmented: {
      trackBg: jojoColors.paperDeep,
      trackPadding: 0,
      itemSelectedBg: jojoColors.magenta,
      itemSelectedColor: jojoColors.gold,
      itemHoverBg: jojoColors.paper,
      itemColor: jojoColors.inkMuted,
      itemHoverColor: jojoColors.ink,
      borderRadius: 0,
      borderRadiusSM: 0,
      borderRadiusLG: 0,
      controlHeight: 40,
    },
    Badge: {
      textFontSize: 12,
      textFontWeight: 900,
      statusSize: 10,
      dotSize: 10,
    },
    Divider: {
      colorSplit: jojoColors.ink,
      orientationMargin: 0.08,
    },
    Breadcrumb: {
      itemColor: jojoColors.inkMuted,
      lastItemColor: jojoColors.ink,
      linkColor: jojoColors.magenta,
      linkHoverColor: jojoColors.purpleHot,
      separatorColor: jojoColors.ink,
      separatorMargin: 10,
      fontSize: 14,
    },
    Pagination: {
      itemActiveBg: jojoColors.purple,
      itemSize: 36,
      itemSizeSM: 28,
      borderRadius: 0,
    },
    Collapse: {
      headerBg: jojoColors.gold,
      contentBg: jojoColors.paper,
      borderRadiusLG: 0,
      headerPadding: "14px 18px",
      contentPadding: "14px 18px",
    },
    Timeline: {
      tailColor: jojoColors.ink,
      dotBg: jojoColors.paper,
      itemPaddingBottom: 24,
    },
    Spin: {
      colorPrimary: jojoColors.magenta,
      contentHeight: 440,
      dotSize: 24,
      dotSizeSM: 16,
      dotSizeLG: 36,
    },
    Result: {
      titleFontSize: 26,
      subtitleFontSize: 15,
      iconFontSize: 72,
    },
    Empty: {
      colorTextDisabled: jojoColors.inkMuted,
    },
    Anchor: {
      linkPaddingBlock: 6,
      linkPaddingInlineStart: 18,
    },
    FloatButton: {
      colorBgElevated: jojoColors.purple,
    },
    Tree: {
      directoryNodeSelectedBg: jojoColors.standAura,
      directoryNodeSelectedColor: jojoColors.ink,
      nodeSelectedBg: jojoColors.standAura,
      nodeHoverBg: jojoColors.paperDeep,
      titleHeight: 28,
    },
    Transfer: {
      listWidth: 220,
      itemHeight: 36,
    },
    Upload: {
      actionsColor: jojoColors.magenta,
    },
    Rate: {
      starColor: jojoColors.gold,
      starSize: 22,
    },
    Statistic: {
      titleFontSize: 14,
      contentFontSize: 28,
    },
    Typography: {
      titleMarginTop: "0.8em",
      titleMarginBottom: "0.4em",
    },
    Form: {
      labelFontSize: 14,
      labelColor: jojoColors.ink,
      labelRequiredMarkColor: jojoColors.magenta,
      itemMarginBottom: 22,
    },
  },
};

export default jojoTheme;
